### ISSUE TITLE
Use creator (not depositor) lastname for metadata

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/dvcurator-python#13]
Since there can be >1 creators, we'd need to make sure we capture those cases. Prefered behavior would be:

1 author: author1lastname - 
2 authors: author1lastnmae-author2lastname - 
3+ authors author1lastname-et-al -

**Comment by mccallc** [comment]
Implemented: https://github.com/QualitativeDataRepository/dvcurator-python/blob/27fc5baa022d9b1d424d1d37dd592dd7c291e019/dvcurator/rename.py#L24
