### ISSUE TITLE
PDF metadata doesn't currently include filename

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/dvcurator-python#2]
The respective line is [commented out](https://github.com/QualitativeDataRepository/dvcurator-python/blob/master/dvcurator/pdf_metadata.py#L58), as is the [erasing of all other metadata](https://github.com/QualitativeDataRepository/dvcurator-python/blob/master/dvcurator/pdf_metadata.py#L52) (which is probably a good idea to do)

**Comment by mccallc** [comment]
both points addressed in commit 883bc77ec650bf75f2b01d2f311b7be639998106
