### ISSUE TITLE
Clarify build/versioning process

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/dvcurator-python#3]
Currently, automatic builds fail because they're We should probably do proper semantic versioning. Could we mint a 0.0.1 release and then automatically incrementally tag on build? There's really no cost to having some arbitrarily large number in the end. Alternatively, we keep the build workflow manual. I'm also OK with that.
Suggestions for other options welcome. 

If we can display the version number in the tool, that'd be helpful for error reporting.

**Comment by mccallc** [comment]
Process is detailed in https://qualitativedatarepository.github.io/dvcurator-python/dev.html#running-compiling

Main overview: create new tag, and new release is built with the tag as the version number
